// ng-app/src/app/pages/dashboard/dashboard.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  template: `
    <div class="mb-8">
      <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 class="text-3xl font-bold text-foreground mb-2">¡Buen día, Ara Moreno! 👋</h1>
          <p class="text-muted-foreground capitalize">{{ today }}</p>
        </div>
        <div class="flex items-center space-x-3 mt-4 sm:mt-0">
          <button class="inline-flex items-center space-x-2 rounded-md bg-primary text-white px-3 py-2 text-sm shadow">
            <span class="text-white">Nuevo Hábito</span>
          </button>
        </div>
      </div>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
      <div class="rounded-lg border border-border/50 bg-background">
        <div class="p-6">
          <div class="flex items-center justify-between">
            <div>
              <p class="text-sm font-medium text-muted-foreground">Hoy Completados</p>
              <p class="text-2xl font-bold text-foreground">{{ completed }}/{{ total }}</p>
            </div>
            <div class="p-3 bg-primary/10 rounded-lg">
              <span class="text-primary font-semibold">✓</span>
            </div>
          </div>
          <div class="mt-4">
            <div class="h-2 bg-muted rounded">
              <div class="h-2 bg-primary rounded" [style.width.%]="progress"></div>
            </div>
            <p class="text-xs text-muted-foreground mt-2">{{ progress | number:'1.0-0' }}% completado</p>
          </div>
        </div>
      </div>
      <div class="rounded-lg border border-border/50 bg-background p-6">
        <p class="text-sm font-medium text-muted-foreground">Racha Actual</p>
        <p class="text-2xl font-bold text-foreground">7 días</p>
      </div>
      <div class="rounded-lg border border-border/50 bg-background p-6">
        <p class="text-sm font-medium text-muted-foreground">Esta Semana</p>
        <p class="text-2xl font-bold text-foreground">23/35</p>
      </div>
      <div class="rounded-lg border border-border/50 bg-background p-6">
        <p class="text-sm font-medium text-muted-foreground">Logros</p>
        <p class="text-2xl font-bold text-foreground">12</p>
      </div>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
      <div class="lg:col-span-2">
        <div class="rounded-lg border border-border/50 bg-background">
          <div class="p-6 border-b border-border/50">
            <div class="flex items-center justify-between">
              <span class="font-semibold">Hábitos de Hoy</span>
              <span class="inline-flex items-center space-x-1 text-xs rounded bg-muted px-2 py-1">5 pendientes</span>
            </div>
            <p class="text-sm text-muted-foreground mt-1">Mantén tu momento y completa tus hábitos diarios</p>
          </div>
          <div class="p-6 space-y-4">
            <div *ngFor="let habit of habits" class="flex items-center space-x-4 p-4 rounded-lg border border-border/50 hover:border-border transition-colors">
              <button class="p-2 rounded-full text-muted-foreground hover:text-foreground" (click)="toggle(habit)">
                <span *ngIf="habit.completed >= habit.target">✓</span>
                <span *ngIf="habit.completed < habit.target">○</span>
              </button>
              <div class="p-2 rounded-lg" [ngClass]="habit.color">
                <span class="text-xs">{{ habit.icon }}</span>
              </div>
              <div class="flex-1 min-w-0">
                <div class="flex items-center justify-between mb-2">
                  <h3 class="font-medium" [class.line-through]="habit.completed>=habit.target" [class.text-muted-foreground]="habit.completed>=habit.target">{{ habit.name }}</h3>
                  <div class="flex items-center space-x-2">
                    <span class="text-sm text-muted-foreground">{{ habit.completed }}/{{ habit.target }} {{ habit.unit }}</span>
                  </div>
                </div>
                <div class="flex items-center space-x-2">
                  <div class="flex-1 h-2 bg-muted rounded">
                    <div class="h-2 bg-primary rounded" [style.width.%]="(habit.completed/ habit.target)*100"></div>
                  </div>
                </div>
              </div>
              <button class="p-2 rounded hover:bg-muted">⋯</button>
            </div>
          </div>
        </div>
      </div>
      <div class="space-y-6">
        <div class="rounded-lg border border-primary/20 bg-gradient-to-br from-primary/5 to-primary/10 p-6">
          <div class="text-primary font-semibold mb-2">¡Motivación!</div>
          <p class="text-foreground font-medium mb-4">"¡Vas excelente! Has completado {{ completed }} hábitos hoy. ¡Sigue así!"</p>
          <div class="text-sm text-muted-foreground">Solo quedan {{ total - completed }} para completar el día</div>
        </div>
      </div>
    </div>
  `
})
export class DashboardComponent {
  today = new Date().toLocaleDateString('es-ES', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
  habits = [
    { id: '1', name: 'Correr 30 minutos', color: 'text-red-500 bg-red-500/10', target: 1, completed: 1, unit: 'sesión', icon: '🏃' },
    { id: '2', name: 'Beber 2 litros de agua', color: 'text-blue-500 bg-blue-500/10', target: 8, completed: 5, unit: 'vasos', icon: '💧' },
    { id: '3', name: 'Ahorrar $50', color: 'text-green-500 bg-green-500/10', target: 50, completed: 30, unit: 'USD', icon: '💰' },
    { id: '4', name: 'Lista de compras semanal', color: 'text-orange-500 bg-orange-500/10', target: 1, completed: 0, unit: 'lista', icon: '🛒' },
    { id: '5', name: 'Meditar 15 minutos', color: 'text-purple-500 bg-purple-500/10', target: 1, completed: 1, unit: 'sesión', icon: '⭐' }
  ];
  get completed() { return this.habits.filter(h => h.completed >= h.target).length; }
  get total() { return this.habits.length; }
  get progress() { return (this.completed / this.total) * 100; }
  toggle(habit: any) {
    if (habit.completed >= habit.target) {
      habit.completed = Math.max(0, habit.completed - 1);
    } else {
      habit.completed = Math.min(habit.target, habit.completed + 1);
    }
  }
}

// client/pages/Dashboard.tsx
import { useState } from "react";
import HabitDialog from "@/components/HabitDialog";
import ProgressCharts from "@/components/ProgressCharts";
import NotificationsPanel from "@/components/NotificationsPanel";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import {
  CheckCircle2,
  Circle,
  TrendingUp,
  Target,
  Calendar as CalendarIcon,
  Flame,
  Plus,
  MoreHorizontal,
  Droplets,
  Dumbbell,
  DollarSign,
  ShoppingCart,
  Star,
  Award,
  Zap,
  Clock,
  ArrowUp,
  ArrowDown,
} from "lucide-react";
import Navigation from "@/components/Navigation";
import { useHabits, Habit as HabitType } from "@/contexts/HabitsContext";
import { toast } from "@/hooks/use-toast";
import { useHabitReminders } from "@/hooks/use-habit-reminders";

type Habit = HabitType;

export default function Dashboard() {
  useHabitReminders();
  const { habits, addHabit, updateHabit } = useHabits();
  const [habitDialogOpen, setHabitDialogOpen] = useState(false);
  const [editingHabit, setEditingHabit] = useState<Habit | undefined>(undefined);
  const [userName] = useState("Ara Moreno");

  const today = new Date().toLocaleDateString("es-ES", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const completedHabitsToday = habits.filter((h) => h.completedToday).length;
  const totalHabits = habits.length || 1;
  const completionPercentage = (completedHabitsToday / totalHabits) * 100;

  const toggleHabit = (habitId: string) => {
    const h = habits.find((x) => x.id === habitId);
    if (!h) return;
    const newCompleted = h.completedToday ? Math.max(0, h.completed - 1) : Math.min(h.target, h.completed + 1);
    updateHabit(habitId, {
      completed: newCompleted,
      completedToday: !h.completedToday,
      streak: !h.completedToday ? h.streak + 1 : h.streak,
      lastCompleted: !h.completedToday ? new Date().toISOString().split("T")[0] : h.lastCompleted,
    });
  };

  const incrementHabit = (habitId: string) => {
    const h = habits.find((x) => x.id === habitId);
    if (!h || h.completed >= h.target) return;
    const newCompleted = h.completed + 1;
    updateHabit(habitId, {
      completed: newCompleted,
      completedToday: newCompleted >= h.target,
      lastCompleted: newCompleted >= h.target ? new Date().toISOString().split("T")[0] : h.lastCompleted,
    });
  };

  return (
    <div className="min-h-screen bg-background">
      <Navigation />

      <div className="max-w-7xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
        <div className="mb-8">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between">
            <div>
              <h1 className="text-3xl font-bold text-foreground mb-2">¡Buen día, {userName}! 👋</h1>
              <p className="text-muted-foreground capitalize">{today}</p>
            </div>
            <div className="flex items-center space-x-3 mt-4 sm:mt-0">
              <NotificationsPanel />
              <Button
                className="flex items-center space-x-2"
                onClick={() => {
                  setEditingHabit(undefined);
                  setHabitDialogOpen(true);
                }}
              >
                <Plus className="h-4 w-4" />
                <span>Nuevo Hábito</span>
              </Button>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
          <Card>
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Hoy Completados</p>
                  <p className="text-2xl font-bold text-foreground">
                    {completedHabitsToday}/{habits.length}
                  </p>
                </div>
                <div className="p-3 bg-primary/10 rounded-lg">
                  <CheckCircle2 className="h-6 w-6 text-primary" />
                </div>
              </div>
              <div className="mt-4">
                <Progress value={completionPercentage} className="h-2" />
                <p className="text-xs text-muted-foreground mt-2">{Math.round(completionPercentage)}% completado</p>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Racha Actual</p>
                  <p className="text-2xl font-bold text-foreground">7 días</p>
                </div>
                <div className="p-3 bg-orange-500/10 rounded-lg">
                  <Flame className="h-6 w-6 text-orange-500" />
                </div>
              </div>
              <div className="flex items-center mt-4 text-success">
                <ArrowUp className="h-4 w-4 mr-1" />
                <span className="text-sm font-medium">+2 desde ayer</span>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Esta Semana</p>
                  <p className="text-2xl font-bold text-foreground">23/35</p>
                </div>
                <div className="p-3 bg-blue-500/10 rounded-lg">
                  <CalendarIcon className="h-6 w-6 text-blue-500" />
                </div>
              </div>
              <div className="flex items-center mt-4 text-success">
                <TrendingUp className="h-4 w-4 mr-1" />
                <span className="text-sm font-medium">66% completado</span>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Logros</p>
                  <p className="text-2xl font-bold text-foreground">12</p>
                </div>
                <div className="p-3 bg-yellow-500/10 rounded-lg">
                  <Award className="h-6 w-6 text-yellow-500" />
                </div>
              </div>
              <div className="flex items-center mt-4 text-warning">
                <Zap className="h-4 w-4 mr-1" />
                <span className="text-sm font-medium">¡3 nuevos!</span>
              </div>
            </CardContent>
          </Card>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center justify-between">
                  <span>Hábitos de Hoy</span>
                  <Badge variant="secondary" className="flex items-center space-x-1">
                    <Clock className="h-3 w-3" />
                    <span>{Math.max(habits.length - completedHabitsToday, 0)} pendientes</span>
                  </Badge>
                </CardTitle>
                <CardDescription>Mantén tu momento y completa tus hábitos diarios</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                {habits.map((habit) => {
                  const Icon = habit.icon;
                  const progress = (habit.completed / habit.target) * 100;
                  const isCompleted = habit.completed >= habit.target;

                  return (
                    <div
                      key={habit.id}
                      className="flex items-center space-x-4 p-4 rounded-lg border border-border/50 hover:border-border transition-colors"
                    >
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => toggleHabit(habit.id)}
                        className={`p-2 rounded-full ${isCompleted ? "text-success bg-success/10" : "text-muted-foreground hover:text-foreground"}`}
                      >
                        {isCompleted ? <CheckCircle2 className="h-5 w-5" /> : <Circle className="h-5 w-5" />}
                      </Button>

                      <div className={`p-2 rounded-lg ${habit.color}`}>
                        <Icon className="h-4 w-4" />
                      </div>

                      <div className="flex-1 min-w-0">
                        <div className="flex items-center justify-between mb-2">
                          <h3 className={`font-medium ${isCompleted ? "line-through text-muted-foreground" : "text-foreground"}`}>
                            {habit.name}
                          </h3>
                          <div className="flex items-center space-x-2">
                            {habit.streak > 0 && (
                              <Badge variant="outline" className="text-xs flex items-center space-x-1">
                                <Flame className="h-3 w-3 text-orange-500" />
                                <span>{habit.streak}</span>
                              </Badge>
                            )}
                            <span className="text-sm text-muted-foreground">
                              {habit.completed}/{habit.target} {habit.unit}
                            </span>
                          </div>
                        </div>

                        <div className="flex items-center space-x-2">
                          <Progress value={progress} className="flex-1 h-2" />
                          {habit.category === "hydration" && habit.completed < habit.target && (
                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={() => incrementHabit(habit.id)}
                              className="text-xs px-2 py-1 h-6"
                            >
                              +1
                            </Button>
                          )}
                        </div>
                      </div>

                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => {
                          setEditingHabit(habit);
                          setHabitDialogOpen(true);
                        }}
                      >
                        <MoreHorizontal className="h-4 w-4" />
                      </Button>
                    </div>
                  );
                })}
              </CardContent>
            </Card>
          </div>

          <div className="space-y-6">
            <Card className="bg-gradient-to-br from-primary/5 to-primary/10 border-primary/20">
              <CardHeader>
                <CardTitle className="flex items-center space-x-2 text-primary">
                  <Zap className="h-5 w-5" />
                  <span>¡Motivación!</span>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-foreground font-medium mb-4">
                  "¡Vas excelente! Has completado {completedHabitsToday} hábitos hoy. ¡Sigue así!"
                </p>
                <div className="flex items-center space-x-2 text-sm text-muted-foreground">
                  <Target className="h-4 w-4" />
                  <span>Solo quedan {Math.max(habits.length - completedHabitsToday, 0)} para completar el día</span>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Categorías</CardTitle>
                <CardDescription>Resumen por tipo de hábito</CardDescription>
              </CardHeader>
              <CardContent className="space-y-3">
                {[
                  { name: "Ejercicio", icon: Dumbbell, count: habits.filter((h) => h.category === "exercise").length, color: "text-red-500" },
                  { name: "Hidratación", icon: Droplets, count: habits.filter((h) => h.category === "hydration").length, color: "text-blue-500" },
                  { name: "Finanzas", icon: DollarSign, count: habits.filter((h) => h.category === "finance").length, color: "text-green-500" },
                  { name: "Compras", icon: ShoppingCart, count: habits.filter((h) => h.category === "shopping").length, color: "text-orange-500" },
                  { name: "Personal", icon: Star, count: habits.filter((h) => h.category === "custom").length, color: "text-purple-500" },
                ].map((category, index) => (
                  <div key={index} className="flex items-center justify-between">
                    <div className="flex items-center space-x-3">
                      <category.icon className={`h-4 w-4 ${category.color}`} />
                      <span className="text-sm font-medium">{category.name}</span>
                    </div>
                    <Badge variant="secondary" className="text-xs">
                      {category.count}
                    </Badge>
                  </div>
                ))}
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center space-x-2">
                  <Award className="h-5 w-5 text-yellow-500" />
                  <span>Logros Recientes</span>
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="flex items-center space-x-3 p-2 rounded-lg bg-muted/50">
                  <div className="w-8 h-8 bg-yellow-500/10 rounded-lg flex items-center justify-center">
                    <Flame className="h-4 w-4 text-yellow-500" />
                  </div>
                  <div>
                    <p className="text-sm font-medium">Racha de 7 días</p>
                    <p className="text-xs text-muted-foreground">¡Imparable!</p>
                  </div>
                </div>
                <div className="flex items-center space-x-3 p-2 rounded-lg bg-muted/50">
                  <div className="w-8 h-8 bg-green-500/10 rounded-lg flex items-center justify-center">
                    <Target className="h-4 w-4 text-green-500" />
                  </div>
                  <div>
                    <p className="text-sm font-medium">Primera semana</p>
                    <p className="text-xs text-muted-foreground">¡Buen comienzo!</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>

        <div className="mt-8">
          <div className="mb-6">
            <h2 className="text-2xl font-bold text-foreground mb-2">Análisis y Progreso</h2>
            <p className="text-muted-foreground">Visualiza tu rendimiento y identifica patrones para mejorar</p>
          </div>
          <ProgressCharts />
        </div>
      </div>

      <HabitDialog
        open={habitDialogOpen}
        onOpenChange={setHabitDialogOpen}
        habit={editingHabit}
        onSave={(newHabit) => {
          if (editingHabit) {
            updateHabit(editingHabit.id, newHabit as any);
          } else {
            addHabit(newHabit as any);
          }
        }}
      />
    </div>
  );
}
